### ISSUE TITLE
Spotify Permissions too broad

### ISSUE THREAD

**Issue by IanMoroney** [remigallego/winampify#23]
It seems like the Spotify permissions being requested are far too broad for comfortable use.
What reason would you have for viewing:
Real name
DOB
Country of residence
Username
Profile picture
Email address

![image](https://user-images.githubusercontent.com/10791260/90501194-dcb30680-e143-11ea-98ad-491fc2186783.png)

This is serious over reach in terms of data needed for this app to function!

**Comment by remigallego** [comment]
@IanMoroney You're right, I basically checked all the boxes to avoid thinking about it and forgot to refine it later. Will change it, thanks!

**Comment by remigallego** [comment]
This should now be fixed on the Backend.
