### ISSUE TITLE
No sound played

### ISSUE THREAD

**Issue by floyd70s** [remigallego/winampify#24]
when I add track to playlist, track advances, but no sound comes out.
no errors or warnings in logs.

<img width="844" alt="Captura de Pantalla 2020-08-21 a la(s) 21 29 14" src="https://user-images.githubusercontent.com/14354411/90945834-61787b80-e3f5-11ea-85ad-8d664f21c348.png">

**Comment by floyd70s** [comment]
> What browser are you using?

safari Versión 13.1.2 (15609.3.5.1.3)

**Comment by remigallego** [comment]
Yeah, at this point only Chrome is fully supported. I will add a TODO to create an alert in case the app is accessed from another browser.
